### ISSUE TITLE
SharpEdge on nginx (WPN-XM) ?

### ISSUE THREAD

**Issue by Apatrid** [srpurdy/SharpEdgeCMS#36]
I have troubles in installing SharpEdge on my local nginx (WPN-XM) server. Always getting 404 error on first step (http://localhost/SharpEdge/install/database_information )? Have you tried this?

**Comment by srpurdy** [comment]
You will want to replace the htaccess file with a nginx configuration instead. Let me see if I can put together something for that. But it is likely the .htaccess file that is causing the issues. I don't have a server right now with nginx. I'll see if I can set something up on a test vps to see.

**Comment by srpurdy** [comment]
Okay so in the /install folder there is a htaccess file replace the code inside with the code below.

# nginx configuration
location / {
rewrite ^(.*)$ /install/index.php?/$1 break;
rewrite js/site_([0-9]+).js /combine.php?version=$1 break;
}

rename the file nginx.conf

In the root there is also an htaccess file replace the code in it to:
# nginx configuration
location / {
rewrite ^(.*)$ /index.php?/$1 break;
rewrite js/site_([0-9]+).js /combine.php?version=$1 break;
}

again rename the file to nginx.conf

Let me know if that solves the problem

**Comment by srpurdy** [comment]
Also I'm downloading WPN-XM so I can try this configuration myself. I'll include a working set into the project once I'm sure it is functional.

**Comment by srpurdy** [comment]
Hi okay so it was a little more complicated.

You need to have something like this in your nginx.conf file.

<pre>
server
{
    listen       127.0.0.1:80;
    server_name  localhost;
    access_log   logs/sharpedge.access.log;
	root         www;
	
	index index.php index.html index.htm;
	
	# set expiration of assets to MAX for caching
        location ~* \.(ico|css|js|gif|jpe?g|png|otf|pdf|flv|woff|swf|xml|txt)(\?[0-9]+)?$ {
                expires max;
                log_not_found off;
        }
	
	location /SharpEdge/ {
        alias /www/SharpEdge;
        try_files $uri $uri/ /SharpEdge/index.php;
    }
	
	location /SharpEdge/install/ {
		alias /www/SharpEdge/install;
        try_files $uri $uri/ /SharpEdge/install/index.php;
    }

    # use fastcgi for all php files
    location ~ \.php$ {
        try_files $uri /index.php =404;
	fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass   127.0.0.1:9100;
        fastcgi_intercept_errors on;
        fastcgi_index  index.php;
        fastcgi_param   SCRIPT_FILENAME $request_filename;
        include        fastcgi_params;
    }

}
</pre>

The paths would obliviously be different in a production system. 

I've update a couple of files in the install folder. So you should update the files in the install folder as well. This is so it plays nice with nginx.
