### ISSUE TITLE
Slider images not showing on sharpedge CMS V 3.42.76

### ISSUE THREAD

**Issue by ebonylegg** [srpurdy/SharpEdgeCMS#38]
Also the slider images are NOT showing on pages. I uploaded slider images, and created a slider show group, But the images do not dislay in the top content of page as I set them to. Instead I see an empty container in place of where the slider is supposed to be.  neither are the sliders showing if added on the side bar or bottom content block

**Comment by srpurdy** [comment]
Did you add the group to the page and loaded the slider widget on the page?

**Comment by srpurdy** [comment]
For example:
After you added your images and selected which you want to be in the slideshow.

By default you need to make a widget group as well (Add the photo widget to the group)
Once this is done. Goto Content->Pages and edit the page you want the slideshow to load on.
You will see on the right side. Slideshow group. Select your group from the drop down.
You will see the 4 widget locations. Load your newly created widget group in one of the 4 locations. (Content Top is usually the location used)
